### ISSUE TITLE
OLS - ComputeError: the plugin panicked

### ISSUE THREAD

**Issue by AdrienDart** [azmyrajab/polars_ols#16]
Hi, 

Just flagging you have an error in the demo notebook for OLS: "ComputeError: the plugin panicked".

Thanks,

Adrien

**Comment by azmyrajab** [comment]
Thanks @AdrienDart  - I forgot to clean up the notebook (had something irrelevant on there). Fixing shortly and bundling into 0.3.1

**Comment by azmyrajab** [comment]
👋  @AdrienDart - fix here https://github.com/azmyrajab/polars_ols/pull/17

& updated notebook [here](https://github.com/azmyrajab/polars_ols/blob/00ad20e38d57553d9087a89ea75fb27836da8375/notebooks/polars_ols_demo.ipynb)

It should run fine now after merge and have updated to include things like what null policy and solve method are and do
