### ISSUE TITLE
Feature Request: Output residual statistics and evaluation measures

### ISSUE THREAD

**Issue by stout-yeoman** [azmyrajab/polars_ols#20]
## Feature Description
I propose the integration of residual statistics and evaluation measures for regression models in the polars-ols package. This feature would include metrics such as R-squared, RMSE (Root Mean Square Error), MAE (Mean Absolute Error), as well as residual statistics such as skew and kurtosis, essential tools for diagnosing the fit of regression models.

## Motivation
Currently, after fitting a regression model using polars-ols, users need to manually calculate performance metrics or use external libraries to evaluate model fit. Especially in the case of rolling ols, this becomes extremely inefficient to do after the coefficients have already been calculated. Integrating these metrics directly into polars-ols would streamline the analysis process, making it more efficient and accessible, especially for new users or those integrating polars into their data science workflows.

## Suggested Implementation
Similarly to coefficients, residual statistics and evaluation measures can be output as structs. User's could indicate which of these they want included, by passing a list of "modes" or flag arguments.

## Benefits
This feature would significantly enhance the utility of polars-ols by providing critical tools for model validation and diagnostics directly within the library. It would improve user experience, reduce dependency on other libraries for model evaluation, and could increase adoption of polars-ols in academic and professional settings.

Happy to discuss this proposal further and contribute to testing.

**Comment by azmyrajab** [comment]
Hi @stout-yeoman, thanks for the feature suggestion - think adding some main statistics metrics like these makes sense. 

We can add residual statistics like R2 / RMSE / etc and also add core statistics on features like t-values + standard errors / confidence bands which might be handy too. The output would be a struct with descriptive field names and either float or list values depending on if it’s a residual or feature statistic (so similar to what you hinted at).

This shouldn’t be too bad to write with the caveat that for L1 and non-negative models the statistics produced would need to be taken as approximate as they’d violate some assumptions which a  straightforward OLS/WLS/Ridge implementation of closed form statistics makes. Can perhaps log a warning for those. For rolling models inverse(XTX) needs to be updated per time step which can be done efficiently but would require a little more effort. perhaps a good starting point is to implement for non moving window models first, then update the rolling/recursive models next (or just implement residual statistics only for those).

I expect to be bandwidth constrained over the next days, but I will try to have a go at this feature request when possible and share with you a draft pull request which you could opine on / test locally

**Comment by azmyrajab** [comment]
Hi @stout-yeoman, apologies for the delay,  latest version should support this for OLS / WLS / Ridge

- Implementation: https://github.com/azmyrajab/polars_ols/blob/main/src/statistics.rs
- Example: https://github.com/azmyrajab/polars_ols/blob/main/tests/test_ols.py#L998 (tested against statsmodels)
- Currently supports MSE, MAE, R2, standard errors, t-values, and p-values
- It returns a struct with scalars for 'residual statistics' (MSE, MAE, R2) and list[f64] values for 'feature statistics' (standard errors, tvalues, pvalues). I also output feature names and coefficients for convenience
- Use `mode="statistics"` to get these out, similar to 'coefficients'. The overhead of producing incremental statistics is fairly small so we just return all of them


***
```
statistics = (df.select(
   pl.col("y").least_squares.ols(pl.col("x1", "x2"), mode="statistics", add_intercept=True)
)
.unnest("statistics")  # results stored in a nested series by default
.explode(["feature_names", "coefficients", "standard_errors", "t_values", "p_values"])
)

print(statistics)
```
```
shape: (3, 8)
┌─────────┬──────────┬─────────┬──────────────┬──────────────┬─────────────┬───────────┬───────────┐
│ r2      ┆ mae      ┆ mse     ┆ feature_name ┆ coefficients ┆ standard_er ┆ t_values  ┆ p_values  │
│ ---     ┆ ---      ┆ ---     ┆ s            ┆ ---          ┆ rors        ┆ ---       ┆ ---       │
│ f64     ┆ f64      ┆ f64     ┆ ---          ┆ f64          ┆ ---         ┆ f64       ┆ f64       │
│         ┆          ┆         ┆ str          ┆              ┆ f64         ┆           ┆           │
╞═════════╪══════════╪═════════╪══════════════╪══════════════╪═════════════╪═══════════╪═══════════╡
│ 0.99631 ┆ 0.061732 ┆ 0.00794 ┆ x1           ┆ 0.977375     ┆ 0.037286    ┆ 26.212765 ┆ 3.0095e-8 │
│ 0.99631 ┆ 0.061732 ┆ 0.00794 ┆ x2           ┆ 0.987413     ┆ 0.037321    ┆ 26.457169 ┆ 2.8218e-8 │
│ 0.99631 ┆ 0.061732 ┆ 0.00794 ┆ const        ┆ 0.000757     ┆ 0.037474    ┆ 0.02021   ┆ 0.98444   │
└─────────┴──────────┴─────────┴──────────────┴──────────────┴─────────────┴───────────┴───────────┘
```

**Comment by gengjun** [comment]
hi @azmyrajab , how to calculate these statistics on a rolling window ?

**Comment by azmyrajab** [comment]
would something like this work? Ie normal polars  rolling applied with the polars ols statistic function. It should still be fast 

https://github.com/azmyrajab/polars_ols/issues/23#issuecomment-2308908438
