### ISSUE TITLE
question on equation

### ISSUE THREAD

**Issue by HPicatto** [azmyrajab/polars_ols#22]
Hi I'd like to understand what is the regression when we do .over("column")
This would not be analogous to one hot, but would be running a regression for each group, is this correct? Do you have any reference on what would be the equation that you are running?

**Comment by azmyrajab** [comment]
Hi @HPicatto, you are exactly right in your thinking: running regression in a `.over` context is  akin to partitioning the data into separate chunks and computing fits / predictions on each.

to achieve one hot encoding over some categorical column you would need to use something like https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.to_dummies.html then pass those expanded columns as features. Notice the polars ols library supports regex for column selection in case you have many encodings

please let me know if that makes sense

**Comment by azmyrajab** [comment]
Hi @mat-ej, unfortunately nothing immediate comes to mind that’s natively supported by the package. That being said, given the model fitting and prediction are lazy one should be able to write cross validation logic which shuffles, assigns partition groups, and computes fit and predict over k groups with polars expressions. It should run pretty fast but would take some effort to write such function 

The answer here is a step in that direction but it does break the lazy eval so it would need to be optimized further to make the most out of polars

https://stackoverflow.com/questions/76564697/polars-shuffle-and-split-dataframe-with-grouping
