### ISSUE TITLE
Error when using .over() in new version of polars 1.x

### ISSUE THREAD

**Issue by chen-001** [azmyrajab/polars_ols#24]
Thanks for this great tool! 
 I see that closed issue [Get coefficients when using .over](https://github.com/azmyrajab/polars_ols/issues/2). 
In April, the new version of polars-ols gave one method to run `.over()`. 
I tested the code shown in the issue. It indeed works on polars 0.x.
But recently polars published some new versions 1.x and made some changes. 
When I run `.over()` with 1.x, for instance, 1.3.0, I receive the error message `ComputeError: this expression cannot run in the group_by context` shown below.
<img width="2437" alt="image" src="https://github.com/user-attachments/assets/ff649dcb-4396-4b96-8ec8-9dc2abd57927">
Any thoughts on this?

**Comment by chen-001** [comment]
Apologies for the previous statement, it's not that there is a problem with the 1.x version as a whole; it's just that there is an issue with version 1.3.0. Version 1.2.1 still works normally. Perhaps it's a temporary bug introduced during the update, and I guess Polars might fix this issue later on.

**Comment by azmyrajab** [comment]
Oh I see, thanks for documenting. Will keep an eye on if things work after 1.3 and otherwise will put a fix in and add a test for a modern version of polars (as haven’t looked at things for a while now)

**Comment by chen-001** [comment]
Thank you for your reply and continued attention. I have noticed that Polars has recently been updated to version 1.4.1. I have tried the .over() function, and it works as expected.
