### ISSUE TITLE
cargo test failed with fatal error unresolved external

### ISSUE THREAD

**Issue by langslike** [azmyrajab/polars_ols#27]
Hey, I am learning to write plugins for polars , when I run "cargo test" command to run the test in lib.rs, I got errors like below, I am using rust 1.80 on windows 10, I need some help to fix it. 
Terminal output:   
[error_code.txt](https://github.com/user-attachments/files/16487707/error_code.txt)

**Comment by azmyrajab** [comment]
Hey @langslike - this is actually a (not ideal) environment related thing pertaining to extension packages built with maturin / pyo3. See  https://pyo3.rs/v0.22.2/faq.html for details. 

You could make it work for cargo, by editing the cargo and pyproject toml to debug but I came to the conclusion, personally, to rely on python tests (wrapping rust functions) instead for projects like these as it was unintuitive edits to config. Tests on lib.rs can just be run manually for you to sanity check things 

hope this makes sense. Haven’t looked at things for a while but ^ was my conclusion when last working on this
