### ISSUE TITLE
how to ignore the warning in rolling_ols min_period

### ISSUE THREAD

**Issue by lesliechiu0525** [azmyrajab/polars_ols#29]
![截屏2024-08-16 10 38 10](https://github.com/user-attachments/assets/60e6bc79-b057-4e59-8979-eeb8ba4b6af4)
I want to ignore this warning

**Comment by azmyrajab** [comment]
Hi @lesliechiu0525, thanks for reporting this. I’ll try to silence this (only print it in rust debug mode) over the weekend. Unfortunately no easy way to toggle it off cleanly right now

**Comment by azmyrajab** [comment]
This is now fixed - it will only print if someone was debugging the rust program

https://github.com/azmyrajab/polars_ols/blob/main/src/least_squares.rs#L902

**Comment by lesliechiu0525** [comment]
> This is now fixed - it will only print if someone was debugging the rust program
> 
> https://github.com/azmyrajab/polars_ols/blob/main/src/least_squares.rs#L902

Thanks
