### ISSUE TITLE
Add rsquared, pvalue, etc to results

### ISSUE THREAD

**Issue by jackaixin** [azmyrajab/polars_ols#31]
Hi @azmyrajab, I’m really a fan of this extension, which speeds up my cross-sectional regression task by more than 10x (i was using statsmodels before).
However, I’m wondering if it’s possible to add other metrics that are available in statsmodels’ results. Common metrics include rsquared, rsquared_adj, pvalue, tvalue, fvalue, nobs, etc. Maybe there can be an argument specifying which metrics are needed so users can pick only the ones required in order not to sacrifice performance.

I would really appreciate your help!

**Comment by azmyrajab** [comment]
Hi @jackaixin - glad the library has been helpful for you. Had a go at this, supporting a majority of what you have requested above (and made it easy to add in more items, if you ever need to and are up for contributing)

See: https://github.com/azmyrajab/polars_ols/issues/20#issuecomment-2308885533

- Use `mode="statistics"` and you will get R2, t-values, p-values, etc.; it should be performant (tried to implement residual statistics with one loop and feature statistics uses `faer` for the xtx inversion)
- It's tested against statsmodels for plain WLS, and I supported ridge as well in case p >> n
